pretrained_model_name_or_path = "sd_xl_base_1.0.safetensors"
max_train_epochs = 12
max_data_loader_n_workers = 4
persistent_data_loader_workers = true
seed = 42
gradient_checkpointing = true
mixed_precision = "bf16"
save_precision = "bf16"
full_bf16 = true
optimizer_type = "AdaFactor"
learning_rate = 2e-4
output_name = "output_name"
log_with = "wandb"
save_every_n_epochs = 1
save_model_as = "safetensors"
vae_batch_size = 4
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
network_dim = 64
cond_emb_dim = 32
flip_aug = false
color_aug = false
resolution = "1024,1024"
batch_size = 8
enable_bucket = false
caption_extension = ".txt"
output_dir = "C:/Users/endma/Desktop/sd-scripts_data_preprocess/output"
logging_dir = "C:/Users/endma/Desktop/sd-scripts_data_preprocess/logs"
train_data_dir = "C:/Users/endma/Desktop/sd-scripts_data_preprocess/data/laion-en-aesthetic_crop/"
conditioning_data_dir = "C:/Users/endma/Desktop/sd-scripts_data_preprocess/data/laion-en-aesthetic_removeLight/"
